baseURL = "/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Ozone"
theme = "docdock"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[params]
  themeVariant = "green"
